# Generated by Django 2.1.5 on 2019-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=45, unique=True)),
                ('Balance', models.DecimalField(decimal_places=6, max_digits=64)),
                ('Percentage', models.DecimalField(decimal_places=10, max_digits=11)),
                ('TxNum', models.IntegerField()),
                ('UpdatedTime', models.DateTimeField()),
                ('UpdatedFromBlock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Hash', models.CharField(max_length=66, unique=True)),
                ('Timestamp', models.DateTimeField()),
                ('Miner', models.CharField(max_length=45)),
                ('TxNum', models.IntegerField()),
                ('Size', models.IntegerField()),
                ('Nonce', models.CharField(max_length=66)),
                ('GasUsed', models.DecimalField(decimal_places=0, max_digits=64)),
                ('GasLimit', models.DecimalField(decimal_places=0, max_digits=64)),
                ('AvgGasPrice', models.DecimalField(decimal_places=0, max_digits=64)),
                ('Difficulty', models.DecimalField(decimal_places=0, max_digits=50)),
                ('TotalDifficulty', models.DecimalField(decimal_places=0, max_digits=50)),
                ('Reward', models.DecimalField(decimal_places=18, max_digits=20)),
                ('UncleReward', models.DecimalField(decimal_places=18, max_digits=20)),
                ('ExtraData', models.CharField(max_length=66)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TxHash', models.CharField(max_length=66, unique=True)),
                ('BlockNum', models.IntegerField()),
                ('Timestamp', models.DateTimeField()),
                ('Status', models.CharField(max_length=45)),
                ('From', models.CharField(max_length=45)),
                ('To', models.CharField(max_length=45)),
                ('Value', models.DecimalField(decimal_places=6, max_digits=64)),
                ('GasUsed', models.DecimalField(decimal_places=0, max_digits=64)),
                ('GasLimit', models.DecimalField(decimal_places=0, max_digits=64)),
                ('GasPrice', models.DecimalField(decimal_places=0, max_digits=64)),
                ('TxFee', models.DecimalField(decimal_places=6, max_digits=64)),
                ('Nonce', models.CharField(max_length=66)),
            ],
        ),
    ]
